---
# tasks file for chriswayg.lxctemplate

- name: Include maketemplate.yml
  include: maketemplate.yml
  when: lxctemplate_make

- name: Include container.yml
  include: container.yml
  when: lxctemplate_container
